"""initial_schema

Revision ID: fc7a6e48c248
Revises: 
Create Date: 2026-08-17 14:45:27.891796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc7a6e48c248'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('yen', sa.BigInteger(), server_default=sa.text('60000'), nullable=False),
    sa.Column('club_tier', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('vip_interior', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('premium_bar', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('neon_sign', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('etiquette', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('victory', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('defeat', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('club_tier IN (1, 2, 3)', name='check_club_tier_range'),
    sa.PrimaryKeyConstraint('device_id')
    )
    op.create_table('shift_history',
    sa.Column('shift_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('club_tier', sa.SmallInteger(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('guests_served', sa.SmallInteger(), nullable=False),
    sa.Column('guests_angry', sa.SmallInteger(), nullable=False),
    sa.Column('bomzh_blocked', sa.SmallInteger(), nullable=False),
    sa.Column('bomzh_placated', sa.SmallInteger(), nullable=False),
    sa.Column('gross_yen', sa.BigInteger(), nullable=False),
    sa.Column('vip_tips_yen', sa.BigInteger(), nullable=False),
    sa.Column('rent_yen', sa.BigInteger(), nullable=False),
    sa.Column('fot_yen', sa.BigInteger(), nullable=False),
    sa.Column('bouncer_yen', sa.BigInteger(), nullable=False),
    sa.Column('bomzh_loss_yen', sa.BigInteger(), nullable=False),
    sa.Column('net_yen', sa.BigInteger(), nullable=False),
    sa.Column('clamped', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['users.device_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('shift_id')
    )
    op.create_index(op.f('ix_shift_history_device_id'), 'shift_history', ['device_id'], unique=False)
    op.create_table('user_hostesses',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('hostess_id', sa.String(length=8), nullable=False),
    sa.Column('hired', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('stamina', sa.SmallInteger(), server_default=sa.text('100'), nullable=False),
    sa.CheckConstraint("hostess_id IN ('YUKI', 'MIRA', 'SAKURA', 'NIKA', 'LUNA')", name='check_valid_hostess_id'),
    sa.CheckConstraint('stamina BETWEEN 0 AND 100', name='check_stamina_range'),
    sa.ForeignKeyConstraint(['device_id'], ['users.device_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('device_id', 'hostess_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_hostesses')
    op.drop_index(op.f('ix_shift_history_device_id'), table_name='shift_history')
    op.drop_table('shift_history')
    op.drop_table('users')
    # ### end Alembic commands ###